"""Rotas do hub de integrações do Life (`/v1/life/integrations`).

Sub-router autocontido, montado por ``create_life_router`` dentro do prefixo
``/v1/life`` — a mesma autenticação por bearer de usuário, repetida aqui de
propósito para que este módulo não dependa do router principal.

Não confundir com ``openjarvis.server.connectors_router``: aquele é a
superfície single-operator (instâncias globais, tokens em ~/.openjarvis) e
não pode ser montado num app multi-cliente. Este fala apenas com
:class:`openjarvis.life.integrations.IntegrationsStore`, que é tenant-scoped
e fail-closed por construção.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from fastapi import APIRouter, Depends, HTTPException
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, ConfigDict, Field, field_validator

from openjarvis.life import LifeContext
from openjarvis.life.app_attest import (
    AppAttestAssertionProof,
    AppAttestError,
    AppAttestStore,
)
from openjarvis.life.integrations import (
    PROVIDERS,
    CredentialVault,
    IntegrationsError,
    IntegrationsStore,
    IntegrationUnavailableError,
    UnknownProviderError,
)
from openjarvis.life.tenancy import User

_bearer = HTTPBearer(auto_error=False)
_APPLE_CALENDAR_SCOPES = frozenset({"events.read", "events.write"})


class DeviceGrantRequest(BaseModel):
    """Bounded native permission receipt; it contains no credential."""

    model_config = ConfigDict(extra="forbid")

    granted_scopes: List[str] = Field(min_length=1, max_length=8)
    device_id: str = Field(min_length=8, max_length=128)
    device_label: str = Field(default="", max_length=120)
    app_attest: Optional[AppAttestAssertionProof] = None

    @field_validator("granted_scopes")
    @classmethod
    def validate_scopes(cls, values: List[str]) -> List[str]:
        normalized = [value.strip() for value in values]
        if any(not value or len(value) > 80 for value in normalized):
            raise ValueError("Each granted scope must contain 1 to 80 characters")
        return normalized


class AppAttestChallengeRequest(BaseModel):
    """Request a one-time challenge bound to one privileged operation."""

    model_config = ConfigDict(extra="forbid")

    purpose: Literal["attest", "device_grant", "native_action", "finance"]
    resource_id: str = Field(default="", max_length=128)
    device_id: str = Field(min_length=8, max_length=128)
    confirmation_method: Literal["", "explicit", "voice_explicit"] = ""


class AppAttestRegistrationRequest(BaseModel):
    """Apple-signed attestation for a key generated by this iOS build."""

    model_config = ConfigDict(extra="forbid")

    challenge_id: str = Field(min_length=16, max_length=128)
    challenge: str = Field(min_length=16, max_length=128)
    device_id: str = Field(min_length=8, max_length=128)
    device_label: str = Field(default="", max_length=120)
    key_id: str = Field(min_length=32, max_length=128)
    attestation_object: str = Field(min_length=64, max_length=65536)


class AppAttestStatusRequest(BaseModel):
    """Public identifiers for checking whether an installation is registered."""

    model_config = ConfigDict(extra="forbid")

    device_id: str = Field(min_length=8, max_length=128)
    key_id: str = Field(min_length=32, max_length=128)


def create_integrations_router(
    life: LifeContext,
    *,
    vault: Optional[CredentialVault] = None,
    app_attest: Optional[AppAttestStore] = None,
) -> APIRouter:
    """Monta as rotas de integrações sobre um contexto Life já aberto.

    Sem ``vault`` o padrão é o ``NullCredentialVault`` fail-closed do store:
    este deployment consegue listar, iniciar e desfazer conexões, mas nenhuma
    credencial tem onde ser guardada até um cofre real ser configurado.
    """
    router = APIRouter(tags=["life-integrations"])
    integrations = IntegrationsStore(life, vault=vault)
    attest = app_attest or AppAttestStore(life)

    def current_user(
        credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
    ) -> User:
        """Resolve o bearer do usuário, ou rejeita com 401."""
        if credentials is None or not credentials.credentials:
            raise HTTPException(status_code=401, detail="Missing bearer token")
        user_id = life.users.resolve_token(credentials.credentials)
        if user_id is None:
            raise HTTPException(status_code=401, detail="Invalid or expired token")
        user = life.users.get_user(user_id)
        if user is None:
            raise HTTPException(status_code=401, detail="Unknown user")
        return user

    @router.get("/integrations")
    async def catalog(user: User = Depends(current_user)) -> Dict[str, Any]:
        """Catálogo curado + estado das conexões deste usuário."""
        return integrations.overview(user.id)

    @router.post("/device-attestation/challenge")
    async def device_attestation_challenge(
        body: AppAttestChallengeRequest,
        user: User = Depends(current_user),
    ) -> Dict[str, Any]:
        """Issue one short-lived challenge; no assertion can be replayed."""
        if body.purpose == "attest" and body.resource_id != body.device_id:
            raise HTTPException(
                status_code=400,
                detail="Attestation challenge must target this device.",
            )
        challenge = attest.issue_challenge(
            user.id,
            purpose=body.purpose,
            resource_id=body.resource_id,
        )
        if body.purpose != "attest":
            challenge["client_data"] = attest.client_data(
                purpose=body.purpose,
                challenge=challenge["challenge"],
                user_id=user.id,
                device_id=body.device_id,
                resource_id=body.resource_id,
                confirmation_method=body.confirmation_method,
            )
        return challenge

    @router.post("/device-attestation/register", status_code=201)
    async def register_device_attestation(
        body: AppAttestRegistrationRequest,
        user: User = Depends(current_user),
    ) -> Dict[str, Any]:
        """Trust a device only after validating Apple's attestation chain."""
        try:
            return attest.register_key(
                user.id,
                challenge_id=body.challenge_id,
                challenge=body.challenge,
                device_id=body.device_id,
                key_id=body.key_id,
                attestation_object=body.attestation_object,
                device_label=body.device_label,
            )
        except AppAttestError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc

    @router.post("/device-attestation/status")
    async def device_attestation_status(
        body: AppAttestStatusRequest,
        user: User = Depends(current_user),
    ) -> Dict[str, bool]:
        """Check a non-secret key identifier before attempting re-attestation."""
        return {
            "registered": attest.is_registered(user.id, body.device_id, body.key_id)
        }

    @router.post("/integrations/{provider}/connect")
    async def connect(
        provider: str, user: User = Depends(current_user)
    ) -> Dict[str, Any]:
        """Inicia a conexão: devolve a URL real de autorização, ou o motivo.

        Iniciar nunca conecta nada — o catálogo continua mostrando a conexão
        como inexistente até o callback (futuro) concluir a troca de código.
        """
        try:
            return integrations.begin_authorization(user.id, provider)
        except UnknownProviderError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        except IntegrationUnavailableError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc

    @router.post("/integrations/{provider}/device-grant", status_code=201)
    async def register_device_grant(
        provider: str,
        body: DeviceGrantRequest,
        user: User = Depends(current_user),
    ) -> Dict[str, Any]:
        """Record EventKit access granted by this user's iPhone installation.

        This endpoint is deliberately limited to Apple Calendar until a real
        HealthKit bridge exists. An authenticated client cannot turn a future
        device integration green by posting an aspirational payload.
        """
        if provider not in PROVIDERS:
            raise HTTPException(status_code=404, detail=f"Unknown provider: {provider}")
        if provider == "apple_health":
            raise HTTPException(
                status_code=409,
                detail="A ponte nativa do HealthKit ainda não está disponível.",
            )
        if provider != "apple_calendar":
            raise HTTPException(
                status_code=409,
                detail="Este provedor não usa autorização nativa do iPhone.",
            )
        if set(body.granted_scopes) != _APPLE_CALENDAR_SCOPES:
            raise HTTPException(
                status_code=409,
                detail="O acesso completo ao Calendário não foi concedido.",
            )
        if body.app_attest is None:
            raise HTTPException(
                status_code=409,
                detail="O iPhone não apresentou uma prova App Attest válida.",
            )
        try:
            with life.connection.transaction():
                attest.verify_assertion(
                    user.id,
                    purpose="device_grant",
                    resource_id=provider,
                    confirmation_method="",
                    device_id=body.device_id,
                    challenge_id=body.app_attest.challenge_id,
                    challenge=body.app_attest.challenge,
                    key_id=body.app_attest.key_id,
                    assertion=body.app_attest.assertion,
                )
                connection = integrations.register_device_grant(
                    user.id,
                    provider,
                    granted=body.granted_scopes,
                    device_id=body.device_id,
                    device_label=body.device_label,
                )
        except UnknownProviderError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        except (AppAttestError, IntegrationsError) as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc
        return {"provider": provider, "connection": connection}

    @router.delete("/integrations/{provider}")
    async def disconnect(
        provider: str, user: User = Depends(current_user)
    ) -> Dict[str, Any]:
        """Cancela a autorização pendente e/ou revoga a conexão do usuário."""
        try:
            result = integrations.disconnect(user.id, provider)
        except UnknownProviderError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        if result is None:
            raise HTTPException(
                status_code=404,
                detail="Nenhuma conexão ou autorização pendente deste provedor.",
            )
        return {"provider": provider, "result": result}

    # Exposto para testes e para o wiring futuro (callback OAuth, iOS bridge).
    router.integrations_store = integrations  # type: ignore[attr-defined]
    return router
