"""Rotas do hub de integrações do Life (`/v1/life/integrations`).

Sub-router autocontido, montado por ``create_life_router`` dentro do prefixo
``/v1/life`` — a mesma autenticação por bearer de usuário, repetida aqui de
propósito para que este módulo não dependa do router principal.

Não confundir com ``openjarvis.server.connectors_router``: aquele é a
superfície single-operator (instâncias globais, tokens em ~/.openjarvis) e
não pode ser montado num app multi-cliente. Este fala apenas com
:class:`openjarvis.life.integrations.IntegrationsStore`, que é tenant-scoped
e fail-closed por construção.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Literal, Optional
from urllib.parse import urlencode

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import RedirectResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, ConfigDict, Field, field_validator

from openjarvis.life import LifeContext
from openjarvis.life.app_attest import (
    AppAttestAssertionProof,
    AppAttestError,
    AppAttestStore,
)
from openjarvis.life.integration_sync import (
    IntegrationSyncError,
    IntegrationSyncService,
)
from openjarvis.life.integrations import (
    PROVIDERS,
    CredentialVault,
    IntegrationAuthError,
    IntegrationsError,
    IntegrationsStore,
    IntegrationUnavailableError,
    UnknownProviderError,
)
from openjarvis.life.oauth_providers import OAuthProviderClient
from openjarvis.life.tenancy import User

logger = logging.getLogger(__name__)
_bearer = HTTPBearer(auto_error=False)
_APPLE_CALENDAR_SCOPES = frozenset({"events.read", "events.write"})


class DeviceGrantRequest(BaseModel):
    """Bounded native permission receipt; it contains no credential."""

    model_config = ConfigDict(extra="forbid")

    granted_scopes: List[str] = Field(min_length=1, max_length=8)
    device_id: str = Field(min_length=8, max_length=128)
    device_label: str = Field(default="", max_length=120)
    app_attest: Optional[AppAttestAssertionProof] = None

    @field_validator("granted_scopes")
    @classmethod
    def validate_scopes(cls, values: List[str]) -> List[str]:
        normalized = [value.strip() for value in values]
        if any(not value or len(value) > 80 for value in normalized):
            raise ValueError("Each granted scope must contain 1 to 80 characters")
        return normalized


class AppAttestChallengeRequest(BaseModel):
    """Request a one-time challenge bound to one privileged operation."""

    model_config = ConfigDict(extra="forbid")

    purpose: Literal["attest", "device_grant", "native_action", "finance"]
    resource_id: str = Field(default="", max_length=128)
    device_id: str = Field(min_length=8, max_length=128)
    confirmation_method: Literal["", "explicit", "voice_explicit"] = ""


class AppAttestRegistrationRequest(BaseModel):
    """Apple-signed attestation for a key generated by this iOS build."""

    model_config = ConfigDict(extra="forbid")

    challenge_id: str = Field(min_length=16, max_length=128)
    challenge: str = Field(min_length=16, max_length=128)
    device_id: str = Field(min_length=8, max_length=128)
    device_label: str = Field(default="", max_length=120)
    key_id: str = Field(min_length=32, max_length=128)
    attestation_object: str = Field(min_length=64, max_length=65536)


class AppAttestStatusRequest(BaseModel):
    """Public identifiers for checking whether an installation is registered."""

    model_config = ConfigDict(extra="forbid")

    device_id: str = Field(min_length=8, max_length=128)
    key_id: str = Field(min_length=32, max_length=128)


def create_integrations_router(
    life: LifeContext,
    *,
    vault: Optional[CredentialVault] = None,
    app_attest: Optional[AppAttestStore] = None,
    oauth_client: Optional[OAuthProviderClient] = None,
) -> APIRouter:
    """Monta as rotas de integrações sobre um contexto Life já aberto.

    Sem ``vault`` o padrão é o ``NullCredentialVault`` fail-closed do store:
    este deployment consegue listar, iniciar e desfazer conexões, mas nenhuma
    credencial tem onde ser guardada até um cofre real ser configurado.
    """
    router = APIRouter(tags=["life-integrations"])
    integrations = IntegrationsStore(
        life,
        vault=vault,
        oauth_callback_available=vault is not None and oauth_client is not None,
    )
    sync_service = (
        IntegrationSyncService(life, vault, oauth_client)
        if vault is not None and oauth_client is not None
        else None
    )
    attest = app_attest or AppAttestStore(life)

    def current_user(
        credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
    ) -> User:
        """Resolve o bearer do usuário, ou rejeita com 401."""
        if credentials is None or not credentials.credentials:
            raise HTTPException(status_code=401, detail="Missing bearer token")
        user_id = life.users.resolve_token(credentials.credentials)
        if user_id is None:
            raise HTTPException(status_code=401, detail="Invalid or expired token")
        user = life.users.get_user(user_id)
        if user is None:
            raise HTTPException(status_code=401, detail="Unknown user")
        return user

    @router.get("/integrations")
    async def catalog(user: User = Depends(current_user)) -> Dict[str, Any]:
        """Catálogo curado + estado das conexões deste usuário."""
        return integrations.overview(user.id)

    @router.post("/device-attestation/challenge")
    async def device_attestation_challenge(
        body: AppAttestChallengeRequest,
        user: User = Depends(current_user),
    ) -> Dict[str, Any]:
        """Issue one short-lived challenge; no assertion can be replayed."""
        if body.purpose == "attest" and body.resource_id != body.device_id:
            raise HTTPException(
                status_code=400,
                detail="Attestation challenge must target this device.",
            )
        challenge = attest.issue_challenge(
            user.id,
            purpose=body.purpose,
            resource_id=body.resource_id,
        )
        if body.purpose != "attest":
            challenge["client_data"] = attest.client_data(
                purpose=body.purpose,
                challenge=challenge["challenge"],
                user_id=user.id,
                device_id=body.device_id,
                resource_id=body.resource_id,
                confirmation_method=body.confirmation_method,
            )
        return challenge

    @router.post("/device-attestation/register", status_code=201)
    async def register_device_attestation(
        body: AppAttestRegistrationRequest,
        user: User = Depends(current_user),
    ) -> Dict[str, Any]:
        """Trust a device only after validating Apple's attestation chain."""
        try:
            return attest.register_key(
                user.id,
                challenge_id=body.challenge_id,
                challenge=body.challenge,
                device_id=body.device_id,
                key_id=body.key_id,
                attestation_object=body.attestation_object,
                device_label=body.device_label,
            )
        except AppAttestError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc

    @router.post("/device-attestation/status")
    async def device_attestation_status(
        body: AppAttestStatusRequest,
        user: User = Depends(current_user),
    ) -> Dict[str, bool]:
        """Check a non-secret key identifier before attempting re-attestation."""
        return {
            "registered": attest.is_registered(user.id, body.device_id, body.key_id)
        }

    @router.post("/integrations/{provider}/connect")
    async def connect(
        provider: str, user: User = Depends(current_user)
    ) -> Dict[str, Any]:
        """Inicia a conexão: devolve a URL real de autorização, ou o motivo.

        Iniciar nunca conecta nada — o catálogo continua mostrando a conexão
        como inexistente até o callback concluir a troca de código.
        """
        try:
            return integrations.begin_authorization(user.id, provider)
        except UnknownProviderError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        except IntegrationUnavailableError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc

    def callback_redirect(provider: str, status: str) -> RedirectResponse:
        safe_provider = provider if provider in PROVIDERS else "unknown"
        query = urlencode({"integration": safe_provider, "status": status})
        return RedirectResponse(url=f"/vida?{query}", status_code=303)

    @router.get("/integrations/{provider}/callback")
    def oauth_callback(
        provider: str,
        code: str = Query(default="", max_length=4096),
        state: str = Query(default="", max_length=512),
        error: str = Query(default="", max_length=256),
    ) -> RedirectResponse:
        """Finish OAuth server-side and return to the single-screen Life shell."""
        if error:
            if state:
                try:
                    integrations.discard_authorization(state, provider)
                except IntegrationsError:
                    pass
            return callback_redirect(provider, "error")
        if not state or not code or oauth_client is None:
            return callback_redirect(provider, "error")
        try:
            context = integrations.authorization_context(state, provider)
            credential = oauth_client.exchange(context, code)
            if not set(context.requested_scopes).issubset(credential.granted_scopes):
                raise IntegrationAuthError(
                    "O provedor não concedeu todos os escopos necessários."
                )
            integrations.complete_authorization(
                state,
                granted_scopes=credential.granted_scopes,
                account_label=credential.account_label,
                credential_payload=credential.to_vault_payload(),
            )
        except IntegrationsError:
            try:
                integrations.discard_authorization(state, provider)
            except IntegrationsError:
                pass
            return callback_redirect(provider, "error")
        except Exception:  # noqa: BLE001 - callback must not leak provider details
            logger.exception("Unexpected OAuth callback failure for %s", provider)
            try:
                integrations.discard_authorization(state, provider)
            except IntegrationsError:
                pass
            return callback_redirect(provider, "error")
        return callback_redirect(provider, "connected")

    @router.post("/integrations/{provider}/device-grant", status_code=201)
    async def register_device_grant(
        provider: str,
        body: DeviceGrantRequest,
        user: User = Depends(current_user),
    ) -> Dict[str, Any]:
        """Record EventKit access granted by this user's iPhone installation.

        This endpoint is deliberately limited to Apple Calendar until a real
        HealthKit bridge exists. An authenticated client cannot turn a future
        device integration green by posting an aspirational payload.
        """
        if provider not in PROVIDERS:
            raise HTTPException(status_code=404, detail=f"Unknown provider: {provider}")
        if provider == "apple_health":
            raise HTTPException(
                status_code=409,
                detail="A ponte nativa do HealthKit ainda não está disponível.",
            )
        if provider != "apple_calendar":
            raise HTTPException(
                status_code=409,
                detail="Este provedor não usa autorização nativa do iPhone.",
            )
        if set(body.granted_scopes) != _APPLE_CALENDAR_SCOPES:
            raise HTTPException(
                status_code=409,
                detail="O acesso completo ao Calendário não foi concedido.",
            )
        if body.app_attest is None:
            raise HTTPException(
                status_code=409,
                detail="O iPhone não apresentou uma prova App Attest válida.",
            )
        try:
            with life.connection.transaction():
                attest.verify_assertion(
                    user.id,
                    purpose="device_grant",
                    resource_id=provider,
                    confirmation_method="",
                    device_id=body.device_id,
                    challenge_id=body.app_attest.challenge_id,
                    challenge=body.app_attest.challenge,
                    key_id=body.app_attest.key_id,
                    assertion=body.app_attest.assertion,
                )
                connection = integrations.register_device_grant(
                    user.id,
                    provider,
                    granted=body.granted_scopes,
                    device_id=body.device_id,
                    device_label=body.device_label,
                )
        except UnknownProviderError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        except (AppAttestError, IntegrationsError) as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc
        return {"provider": provider, "connection": connection}

    @router.post("/integrations/{provider}/sync")
    def sync_provider(
        provider: str,
        user: User = Depends(current_user),
    ) -> Dict[str, Any]:
        """Synchronize one connected provider into bounded tenant records."""
        if sync_service is None:
            raise HTTPException(
                status_code=503,
                detail="A sincronização OAuth não está configurada neste servidor.",
            )
        try:
            return sync_service.sync(user.id, provider)
        except UnknownProviderError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        except IntegrationSyncError as exc:
            status_code = (
                502 if exc.reason in {"internal_error", "provider_error"} else 409
            )
            raise HTTPException(status_code=status_code, detail=str(exc)) from exc

    @router.delete("/integrations/{provider}")
    async def disconnect(
        provider: str, user: User = Depends(current_user)
    ) -> Dict[str, Any]:
        """Cancela a autorização pendente e/ou revoga a conexão do usuário."""
        try:
            result = integrations.disconnect(user.id, provider)
        except UnknownProviderError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        if result is None:
            raise HTTPException(
                status_code=404,
                detail="Nenhuma conexão ou autorização pendente deste provedor.",
            )
        return {"provider": provider, "result": result}

    # Exposto para testes e para o wiring nativo do iOS.
    router.integrations_store = integrations  # type: ignore[attr-defined]
    router.integration_sync_service = sync_service  # type: ignore[attr-defined]
    return router
